# Bloco para bloquear domínios não cadastrados
server {
    listen 80 default_server;
    server_name localhost eventos.correvirtual.com.br 127.0.0.1;
}

server {
    listen 80;
    index index.php index.html;
    server_name correvirtual.local borafitness.local localhost 127.0.0.1 ~^192\.168\.\d+\.\d+$ ~^10\.\d+\.\d+\.\d+$;

    root /var/www/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}