# Redireciona HTTP para HTTPS
server {
    listen 80;
    server_name eventos.correvirtual.com.br 129.121.37.184 localhost 127.0.0.1;

    # Mantém a rota do Certbot aberta na porta 80 para futuras renovações
    location /.well-known/acme-challenge/ {
        root /var/www/public;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Configuração Principal HTTPS
server {
    listen 443 ssl;
    server_name eventos.correvirtual.com.br;

    # Aponta para os certificados gerados no Host e mapeados no docker-compose
    ssl_certificate /etc/letsencrypt/live/eventos.correvirtual.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eventos.correvirtual.com.br/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}